spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  # Enabling H2 Console
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none